# Generated by Django 3.1.3 on 2020-12-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
    ]
